# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    form_errors:
        class: TaskBundle\Form\FormErrors
    login_listener:
            class: 'UserBundle\EventListener\LoginListener'
            arguments: ['@security.context', '@doctrine','@session']
            tags:
                - { name: 'kernel.event_listener', event: 'security.interactive_login' }
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    app.user_locale_listener:
        class: AppBundle\EventListener\UserLocaleListener
        arguments: ["@session"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
